version: '3'
services:
    ampq-php:
        build: docker/php
        depends_on:
          - ampq-rabbitmq
        container_name: ampq-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - ampq-net

    ampq-rabbitmq:
        build: docker/rabbit
        container_name: ampq-rabbitmq
        ports:
            - 8082:15672
        environment:
            RABBITMQ_DEFAULT_VHOST: my_vhost
        networks:
            - ampq-net

networks:
    ampq-net:
        driver: bridge